[PHP]
extension_dir = "C:\php-8.3.29-Win32-vs16-x64\ext"
extension=php_curl.dll
extension=php_fileinfo.dll
extension=php_mbstring.dll
extension=php_openssl.dll
extension=php_pdo_mysql.dll
extension=php_mysqli.dll

allow_url_fopen = On
memory_limit = 512M
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 300
date.timezone = UTC
